Repository N0MoreSecr3ts/wraith, pull requests merged in 2022-07, with the labels that each got.

#125 Feature/Makefile help target
  Makefile
Labels: Documentation, Build and Release

#126 Fix/findings UI
  core/bindata.go
  static/index.html
  static/javascripts/application.js
Labels: Bug, UX

#127 fix make test command to not change directory
  Makefile
Labels: Bug, Build and Release

#133 Feature/config filepath
  cmd/root.go
  cmd/scanGithub.go
  cmd/scanGithubEnterprise.go
  cmd/scanGitlab.go
  cmd/scanLocalGitRepo.go
  cmd/scanLocalPath.go
  cmd/updateRules.go
  core/bindata.go
  core/github.go
  core/session.go
Labels: Feature Request
